### PR TITLE
print() is a function in modern Python

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by kacperszurek** [comment]
Hi @cclauss 

Burp extensions don't use pure python but [Jython](http://www.jython.org/).

As far as I know Jython supports [CPython 2.7](https://wiki.python.org/jython/JythonFaq/GeneralInfo) syntax.

So until Jython moves to 3.0 branch this is not so important because this code will be always running under Python 2 environment. @cclauss what do you think?

**Comment by cclauss** [comment]
This PR is designed to run on __both__ Python 2 and Python 3.  The precautionary principle would suggest that merging the PR is a better way to go than not doing so.  These are not earth shattering changes and I understand your logic given that https://github.com/jython/jython3 is taking time.

**Comment by kacperszurek** [comment]
OK I agree. It looks like I don't need to use `print` function because Burp API provides `printOutput`.

I made changes here https://github.com/kacperszurek/burp_wp/commit/9fd1ce8cf8a31bbbdef3af545aec836045f1d49d

**Comment by cclauss** [comment]
Missed [./burp_wp.py line 86](https://github.com/kacperszurek/burp_wp/blob/master/burp_wp.py#L86).

**Comment by kacperszurek** [comment]
No, see: https://github.com/kacperszurek/burp_wp/blob/bapp_store/burp_wp.py#L88

It's on branch not on master.

I am preparing release for BApp store. After I finish, it will be merged into master.

**Pull request closed without merging**
